[package]
name = "gitcash"
authors = ["Danilo Bargen <mail@dbrgn.ch>"]
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
libgitcash = { path = "../libgitcash/" }
tracing = "0.1"
tracing-subscriber = "0.3"
