[package]
name = "libgitcash"
authors = ["Danilo Bargen <mail@dbrgn.ch>"]
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"

[dependencies]
git2 = "0.17.2"
serde = { version = "1", features = ["derive"] }
thiserror = "1"
toml = "0.7"
tracing = "0.1"
