on:
  push:
    branches:
      - main
  pull_request:

name: CI

jobs:

  test:
    name: Build and test crates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.74.0
          override: true
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test

  parse:
    name: Parse demo repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.74.0
          override: true
      - name: Clone repo
        run: git clone https://github.com/coredump-ch/gitcash-demo-repo/
      - name: Build
        run: cargo build
      - name: Create config
        run: echo -e "repo_path = 'gitcash-demo-repo'\naccount = 'pos:fridge'\ngit_name = 'CI'\ngit_email = 'ci@example.com'" > config.toml
      - name: Calculate balances
        run: target/debug/gitcash balances

  rustfmt:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.74.0
          override: true
          components: rustfmt
      - run: cargo fmt -- --check
